import pathlib

lines = [
    '## player.gd',
    '## FPS CharacterBody3D with sphere-aware gravity.',
    '## Gravity always points toward (0,0,0) - the planet centre.',
    '## The player body is kept upright relative to the surface normal.',
    '',
    'extends CharacterBody3D',
    '',
    '@export var move_speed   : float = 10.0',
    '@export var sprint_speed : float = 30.0',
    '@export var jump_force   : float = 8.0',
    '@export var gravity      : float = 9.8',
    '@export var mouse_sens   : float = 0.002',
    '',
    'var _fly_mode  := false',
    'var _pitch     := 0.0',
    '',
    '@onready var _camera : Camera3D = $Camera3D',
    '',
    '',
    'func _ready() -> void:',
    '\tInput.set_mouse_mode(Input.MOUSE_MODE_CAPTURED)',
    '',
    '',
    'func _unhandled_input(event: InputEvent) -> void:',
    '\tif event is InputEventMouseMotion and Input.get_mouse_mode() == Input.MOUSE_MODE_CAPTURED:',
    '\t\t# Yaw: rotate around local up (the surface-normal up vector)',
    '\t\trotate(global_transform.basis.y, -event.relative.x * mouse_sens)',
    '\t\t_pitch = clamp(_pitch - event.relative.y * mouse_sens, -PI * 0.45, PI * 0.45)',
    '\t\t_camera.rotation.x = _pitch',
    '',
    '\tif event.is_action_pressed("ui_cancel"):',
    '\t\tif Input.get_mouse_mode() == Input.MOUSE_MODE_CAPTURED:',
    '\t\t\tInput.set_mouse_mode(Input.MOUSE_MODE_VISIBLE)',
    '\t\telse:',
    '\t\t\tInput.set_mouse_mode(Input.MOUSE_MODE_CAPTURED)',
    '',
    '\tif event is InputEventKey and event.pressed and event.keycode == KEY_F:',
    '\t\t_fly_mode = not _fly_mode',
    '',
    '',
    'func _physics_process(delta: float) -> void:',
    '\t# --- Gravity direction: toward planet centre ---',
    '\tvar up_dir := global_position.normalized()  # points away from centre',
    '\tif up_dir.is_zero_approx():',
    '\t\tup_dir = Vector3.UP',
    '',
    '\t# Align the player upright on the sphere surface',
    '\t_align_to_surface(up_dir)',
    '',
    '\tvar speed := sprint_speed if Input.is_key_pressed(KEY_SHIFT) else move_speed',
    '',
    '\t# Local movement directions (relative to current orientation)',
    '\tvar forward := -global_transform.basis.z',
    '\tvar right   :=  global_transform.basis.x',
    '',
    '\tvar dir := Vector3.ZERO',
    '\tif Input.is_key_pressed(KEY_W): dir += forward',
    '\tif Input.is_key_pressed(KEY_S): dir -= forward',
    '\tif Input.is_key_pressed(KEY_A): dir -= right',
    '\tif Input.is_key_pressed(KEY_D): dir += right',
    '',
    '\tif _fly_mode:',
    '\t\tif Input.is_key_pressed(KEY_SPACE): dir += up_dir',
    '\t\tif Input.is_key_pressed(KEY_CTRL):  dir -= up_dir',
    '\t\tvelocity = dir.normalized() * speed',
    '\telse:',
    '\t\t# Project movement onto the surface tangent plane',
    '\t\tvar tangent_dir := dir - dir.dot(up_dir) * up_dir',
    '',
    '\t\t# Apply gravity (toward centre = negative up)',
    '\t\tvar grav_component: float = velocity.dot(-up_dir)',
    '\t\tif not is_on_floor():',
    '\t\t\tgrav_component += gravity * delta',
    '\t\telif Input.is_key_pressed(KEY_SPACE):',
    '\t\t\tgrav_component = -jump_force  # jump = push away from centre',
    '',
    '\t\t# Reconstruct velocity: tangent movement + gravity along surface normal',
    '\t\tvelocity = tangent_dir.normalized() * speed - up_dir * grav_component',
    '',
    '\tmove_and_slide()',
    '',
    '',
    'func _align_to_surface(up_dir: Vector3) -> void:',
    '\t## Smoothly rotates the player so their local Y axis matches the planet up vector.',
    '\tvar current_up := global_transform.basis.y',
    '\tif current_up.dot(up_dir) > 0.9999:',
    '\t\treturn  # already aligned',
    '',
    '\t# Build a rotation that maps current_up -> up_dir',
    '\tvar rot_axis := current_up.cross(up_dir)',
    '\tif rot_axis.length_squared() < 0.0001:',
    '\t\treturn',
    '\tvar rot_angle := current_up.angle_to(up_dir)',
    '\tvar q := Quaternion(rot_axis.normalized(), rot_angle)',
    '\tglobal_transform.basis = Basis(q) * global_transform.basis',
    '',
]

out = pathlib.Path('F:/Dev/Projects/new-game-project/player/player.gd')
out.write_text('\n'.join(lines), encoding='utf-8')
print(f'Written {out} ({out.stat().st_size} bytes)')
