import pathlib

lines = [
    '[gd_scene format=3 uid="uid://bcsq6iseh61y1"]',
    '',
    '[ext_resource type="VoxelGeneratorGraph" uid="uid://planet_sphere_graph" path="res://eden/planet/planet_sphere_graph.tres" id="1_graph"]',
    '[ext_resource type="Script" uid="uid://qt0nbhc843v7" path="res://player/player.gd" id="2_player"]',
    '',
    '[sub_resource type="VoxelMesherTransvoxel" id="VoxelMesherTransvoxel_1"]',
    '',
    '[sub_resource type="VoxelFormat" id="VoxelFormat_1"]',
    '',
    '[sub_resource type="StandardMaterial3D" id="StandardMaterial3D_1"]',
    'shading_mode = 2',
    'diffuse_mode = 3',
    'vertex_color_use_as_albedo = true',
    'albedo_color = Color(0.35, 0.55, 0.2, 1)',
    '',
    '[sub_resource type="Environment" id="Environment_1"]',
    'background_mode = 2',
    'ambient_light_source = 2',
    'ambient_light_color = Color(0.5, 0.5, 0.5, 1)',
    'ambient_light_energy = 0.4',
    '',
    '[sub_resource type="CapsuleShape3D" id="CapsuleShape3D_1"]',
    'radius = 0.4',
    'height = 1.8',
    '',
    '[node name="PlanetTest" type="Node3D"]',
    '',
    '[node name="WorldEnvironment" type="WorldEnvironment" parent="."]',
    'environment = SubResource("Environment_1")',
    '',
    '[node name="Sun" type="DirectionalLight3D" parent="."]',
    'transform = Transform3D(0.866, -0.353, 0.354, 0, 0.707, 0.707, -0.5, -0.612, 0.612, 0, 45000, 0)',
    'light_energy = 1.5',
    'shadow_enabled = true',
    '',
    # Copy exact settings from the working scene
    '[node name="VoxelLodTerrain" type="VoxelLodTerrain" parent="."]',
    'generator = ExtResource("1_graph")',
    'mesher = SubResource("VoxelMesherTransvoxel_1")',
    'format = SubResource("VoxelFormat_1")',
    'gi_mode = 2',
    'view_distance = 2048',
    'lod_count = 20',
    'lod_distance = 128.0',
    'secondary_lod_distance = 128.0',
    'material = SubResource("StandardMaterial3D_1")',
    'normalmap_enabled = true',
    'normalmap_use_gpu = true',
    'use_gpu_generation = true',
    'streaming_system = 1',
    '',
    # Player spawns 1000m above surface at north pole (radius 40000)
    '[node name="Player" type="CharacterBody3D" parent="."]',
    'transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 41000, 0)',
    'script = ExtResource("2_player")',
    '',
    '[node name="CollisionShape3D" type="CollisionShape3D" parent="Player"]',
    'transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0.9, 0)',
    'shape = SubResource("CapsuleShape3D_1")',
    '',
    '[node name="Camera3D" type="Camera3D" parent="Player"]',
    'transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0.7, 0)',
    'current = true',
    'fov = 85.0',
    'near = 0.1',
    'far = 16384.0',
    '',
    # VoxelViewer under Player so it follows the camera
    '[node name="VoxelViewer" type="VoxelViewer" parent="Player"]',
    'requires_visuals = true',
    '',
]

out = pathlib.Path('F:/Dev/Projects/new-game-project/scenes/terrain_test.tscn')
out.write_text('\n'.join(lines), encoding='utf-8')
print(f'Written: {out}')
