import pathlib

lines = [
    '[gd_scene format=3 uid="uid://bcsq6iseh61y1"]',
    '',
    '[ext_resource type="Resource" path="res://eden/planet/planet_generator.tres" id="1_gen"]',
    '[ext_resource type="Script" uid="uid://qt0nbhc843v7" path="res://player/player.gd" id="2_player"]',
    '',
    '[sub_resource type="Environment" id="Environment_1"]',
    'background_mode = 2',
    'ambient_light_source = 2',
    'ambient_light_color = Color(0.5, 0.5, 0.5, 1)',
    'ambient_light_energy = 0.4',
    '',
    '[sub_resource type="VoxelMesherTransvoxel" id="VoxelMesherTransvoxel_1"]',
    '',
    '[sub_resource type="VoxelFormat" id="VoxelFormat_1"]',
    '',
    '[sub_resource type="StandardMaterial3D" id="StandardMaterial3D_1"]',
    'shading_mode = 2',
    'diffuse_mode = 3',
    'albedo_color = Color(0.35, 0.55, 0.2, 1)',
    '',
    '[sub_resource type="CapsuleShape3D" id="CapsuleShape3D_1"]',
    'radius = 0.4',
    'height = 1.8',
    '',
    '[node name="PlanetTest" type="Node3D" unique_id=170994852]',
    '',
    '[node name="WorldEnvironment" type="WorldEnvironment" parent="." unique_id=204202014]',
    'environment = SubResource("Environment_1")',
    '',
    # Sun: above the north pole at y=45000, angled downward
    '[node name="Sun" type="DirectionalLight3D" parent="." unique_id=94706893]',
    'transform = Transform3D(0.866, -0.353, 0.354, 0, 0.707, 0.707, -0.5, -0.612, 0.612, 0, 45000, 0)',
    'light_energy = 1.5',
    'shadow_enabled = true',
    '',
    # VoxelLodTerrain: lod_count=12 for a 40km planet, view_distance=2000
    '[node name="VoxelLodTerrain" type="VoxelLodTerrain" parent="." unique_id=108786627]',
    'generator = ExtResource("1_gen")',
    'mesher = SubResource("VoxelMesherTransvoxel_1")',
    'format = SubResource("VoxelFormat_1")',
    'lod_count = 10',
    'view_distance = 2000.0',
    'material = SubResource("StandardMaterial3D_1")',
    'collision_lod_count = 3',
    '',
    # Player: spawned 800m above surface at north pole (radius=40000 + 800)
    '[node name="Player" type="CharacterBody3D" parent="." unique_id=774104438]',
    'transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 40800, 0)',
    'script = ExtResource("2_player")',
    '',
    '[node name="CollisionShape3D" type="CollisionShape3D" parent="Player" unique_id=375671402]',
    'transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0.9, 0)',
    'shape = SubResource("CapsuleShape3D_1")',
    '',
    '[node name="Camera3D" type="Camera3D" parent="Player" unique_id=2019788534]',
    'transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0.7, 0)',
    'current = true',
    'fov = 85.0',
    'near = 0.1',
    'far = 8192.0',
    '',
    # VoxelViewer is a child of Player so it follows the player position
    '[node name="VoxelViewer" type="VoxelViewer" parent="Player" unique_id=458615776]',
    'requires_visuals = true',
    '',
]

out = pathlib.Path('F:/Dev/Projects/new-game-project/scenes/terrain_test.tscn')
out.write_text('\n'.join(lines), encoding='utf-8')
print(f'Written {out} ({out.stat().st_size} bytes)')
