#!/usr/bin/env python3
Import("env")
Import("env_modules")

env_stamps = env_modules.Clone()

# We include voxel module headers which require ZN_GODOT to be defined
env_stamps.Append(CPPDEFINES=["ZN_GODOT"])

# Sources
module_sources = [
    "register_types.cpp",
    "terrain_stamp.cpp",
    "terrain_stamp_placer.cpp",
]

env_stamps.add_source_files(env.modules_sources, module_sources)
