#!/usr/bin/env python

Import("env")
Import("env_modules")

env_eden_foliage = env_modules.Clone()

module_obj = []
env_eden_foliage.add_source_files(module_obj, "*.cpp")

env.modules_sources += module_obj
